### ISSUE TITLE
Create, Read, Delete operations for user

### ISSUE THREAD

**Issue by lipa44** [is-tech-y24-1/Do-Svyazi.User#3]
- [x] Create `MessengerUser` (проверить что не зареган такой же NickName)
- [x] Delete `MessengerUser`
- [x] Get `MessengerUser` (by Id, by NickName)
- [x] Получить все Id чатов у `MessengerUser`
- [x] Получить все чаты у `MessengerUser`
- [x] Получить роль `MessengerUser` в определённом чате

**Comment by iskander-faggod** [comment]
#22

**Comment by iskander-faggod** [comment]
#4
